x-google-marketplace:
  schemaVersion: v2

  applicationApiVersion: v1beta1

  publishedVersion: '0.0.2'
  publishedVersionMetadata:
    releaseNote: >-
      Initial release
    releaseTypes:
      - Feature
    recommended: false

  images:
    '':
      properties:
        imageFull:
          type: FULL
        imageTag:
          type: TAG

properties:
  name:
    type: string
    x-google-marketplace:
      type: NAME
  namespace:
    type: string
    x-google-marketplace:
      type: NAMESPACE
  replicas:
    type: integer
    title: Amplifier Store replica count
    default: 3
    description: The number of Amplifier Store replicas to deploy
  resonanceClientId:
    type: string
    title: Resonance Client ID
    default: 'mock-client-id'
    description: Enter the Resonance Client ID found in the Resonance Developer Settings
  resonanceApiKey:
    type: string
    title: Resonance API Key
    default: 'mock-api-key'
    description: Enter the Resonance API Key generated in the Resonance Developer Settings
    x-google-marketplace:
      type: MASKED_FIELD
  resonanceRedisUrl:
    type: string
    title: Redis URL
    default: 'redis://mock-redis-url'
    description: Enter the URL of the Redis DB that will be used with this amplifier store

required:
  - name
  - namespace
  - replicas
  - resonanceClientId
  - resonanceApiKey
  - resonanceRedisUrl
