x-google-marketplace:
  schemaVersion: v2

  applicationApiVersion: v1beta1

  publishedVersion: '0.0.1'
  publishedVersionMetadata:
    releaseNote: >-
      Initial release
    releaseTypes:
      - Feature
    recommended: false

  images:
    '':
      properties:
        imageFull:
          type: FULL
        imageTag:
          type: TAG

properties:
  name:
    type: string
    x-google-marketplace:
      type: NAME
  namespace:
    type: string
    x-google-marketplace:
      type: NAMESPACE
  replicas:
    type: integer
    title: Amplifier Store replica count
    default: 3
    description: The number of Amplifier Store replicas to deploy
  resonance.clientId:
    type: string
    title: Resonance Client ID
    description: Enter the Resonance Client ID found in the Resonance Developer Settings
  resonance.apiKey:
    type: string
    title: Resonance API Key
    description: Enter the Resonance API Key generated in the Resonance Developer Settings
    x-google-marketplace:
      type: MASKED_FIELD
  resonance.redisUrl:
    type: string
    title: Redis URL
    description: Enter the URL of the Redis DB that will be used with this amplifier store

required:
  - name
  - namespace
  - replicas
  - resonance.clientId
  - resonance.apiKey
  - resonance.redisUrl
