x-google-marketplace:
  schemaVersion: v2

  applicationApiVersion: v1beta1

  publishedVersion: '$TAG'
  publishedVersionMetadata:
    releaseNotes: >-
      Initial release
    releaseTypes:
      - Feature
    recommended: false

  images:
    '':
      properties:
        imageFull:
          type: FULL
        imageTag:
          type: TAG

properties:
  name:
    type: string
    x-google-marketplace:
      type: NAME
  namespace:
    type: string
    x-google-marketplace:
      type: NAMESPACE
  resonanceClientId:
    type: string
    x-google-marketplace:
      type: RESONANCE_CLIENT_ID
  resonanceApiKey:
    type: string
    x-google-marketplace:
      type: RESONANCE_API_KEY
  resonance.redisUrl:
    type: string
    x-google-marketplace:
      type: REDIS_URL

required:
  - name
  - namespace
  - resonanceClientId
  - resonanceApiKey
  - resonance.redisUrl
