properties:
  testerImage:
    type: string
    default: $REGISTRY/tester:$TAG
    x-google-property:
      type: IMAGE
  resonanceClientId:
    type: string
    default: 'mock-client-id'
  resonanceApiKey:
    type: string
    default: 'mock-api-key'
  resonanceRedisUrl:
    type: string
    default: 'redis://mock-redis-url'
